name: Checks

on:
  pull_request:
  push:
    paths-ignore:
      - 'assets/**'
      - '.vscode/**'
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.4
          registry-url: 'https://registry.npmjs.org'

      - name: Install yarn
        run: npm i yarn -g

      - name: Install Dependencies
        run: yarn install
        env:
          # postinstall uses this
          TRANSCRYPT_PASSWORD: ${{ secrets.transcrypt_password }}
          SHOULD_UNLOCK_GIT_CRYPT: "1"

      - name: Build JS
        run: yarn build:js

      - name: Check
        run: yarn && yarn check

      - name: Lint
        run: yarn lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.4
          registry-url: 'https://registry.npmjs.org'

      - name: Install yarn
        run: npm i yarn -g

      - name: Install Dependencies
        run: yarn install
        env:
          # postinstall uses this
          TRANSCRYPT_PASSWORD: ${{ secrets.transcrypt_password }}
          SHOULD_UNLOCK_GIT_CRYPT: "1"

      - name: Install playwright
        run: npx playwright install

      - uses: nick-fields/retry@v3
        name: "Run tests
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        with:
          timeout_minutes: 15
          max_attempts: 2
          command: 'yarn test'
