name: Bento

on:
  push:
    paths:
      - "code/bento/**"
      - "code/tamagui.dev/scripts/build-bento.cjs"
      - "code/tamagui.dev/scripts/upload-bento.cjs"
    branches:
      - master

jobs:
  build-and-upload:
    name: Build & Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install
        with:
          transcrypt_password: ${{ secrets.transcrypt_password }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Link Vercel Project
        run: cd code/tamagui.dev && vercel link --project site --scope=tamagui --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: cd code/tamagui.dev && vercel env pull .env.local --environment production --scope=tamagui --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Bento Components
        run: cd code/tamagui.dev && yarn build:bento

      - name: Upload To Supabase
        run: cd code/tamagui.dev && yarn upload:bento
